### ISSUE TITLE
Multithreading issue

### ISSUE THREAD

**Issue by demglobekkeper** [lincollincol/Amplituda#1]
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.example.chat/files/Documents/amplituda_tmp_values.txt (No such file or directory)

There is a problem that a library doesn't work when you start several files at once in the background thread **getSampleFrom**. 
It works for a single file. But with multiple files it doesn't((
Is it possible to fix it somehow?

```
WaveformOptions.getSampleFrom(file.path) {
      waves = it
}
```

**Comment by lincollincol** [comment]
@demglobekkeper can you share more code or library which implements multithreading in your project? I'd like to reproduce this bug on my device.

**Comment by demglobekkeper** [comment]
thanks for so quick response!
I start every thread by using coroutines. When I have 2+ audio to convert some of them can be converted well and some of them finish with the warning I attached above.

lifecycleScope.launch(Dispatchers.Default) {
            val uri3 = requireContext().resources.openRawResource(audioId) //audioId on of the mp3 file in raw folder
            var waves: IntArray = intArrayOf()

            try {
                val file = File(requireContext().cacheDir, "cacheFileAppeal{Random().nextInt(10000)}.srl")
                FileOutputStream(file).use { output ->
                    val buffer = ByteArray(4 * 1024)
                    var read = 0
                    while (uri3.read(buffer).also { read = it } != -1) {
                        output.write(buffer, 0, read)
                    }
                    output.flush()
                }

                WaveformOptions.getSampleFrom(file.path) {
                    waves = it
                }

                withContext(Dispatchers.Main) {
                    waveformSeekBar.sample = waves
                }
            } catch (e: Exception) {
                e.printStackTrace()
            } finally {
                uri3.close()
            }
        }

**Comment by lincollincol** [comment]
Hello @demglobekkeper, wait for a new waveformSeekBar library version with the new Amplituda version in which this bug was fixed.
