### ISSUE TITLE
Throw exceptions instead of writing logs or add error callback

### ISSUE THREAD

**Issue by tamimattafi** [lincollincol/Amplituda#11]
First of all, thank you for this beautiful library!

I tried to use this library to get wave forms from an MP4 audio file, that was recorded using android AudMediaRecorder.
However, the callback was never called, I thought it was calculating some stuff, but I understood the problem when I started reading the source code.

I wasted sometime to figure that out because i thought if there is something wrong the library will just throw since there is no error handler.

It would be amazing if the library threw exceptions on errors or just returned a callback with a throwable.

**Comment by lincollincol** [comment]
@tamimattafi Hi! Thanks for the feedback. I will try to add it soon.

**Comment by lincollincol** [comment]
Hi @tamimattafi, you can use setErrorListener() for error handling.
`implementation 'com.github.lincollincol:Amplituda:2.0.1'`
I'll update documentation soon, but you can also open Amplituda code and check 'exceptions' package.

Sample code:
```
Amplituda amplituda = new Amplituda();
amplituda.setErrorListener(error -> {
    error.printStackTrace() // Print error message
    if(error instanceof AmplitudaIOException) { // Handle only io exceptions
        System.out.println("IO exception");
    }
    // etc
});
```

**Comment by tamimattafi** [comment]
> Hi @tamimattafi, you can use setErrorListener() for error handling.
> `implementation 'com.github.lincollincol:Amplituda:2.0.1'`
> I'll update documentation soon, but you can also open Amplituda code and check 'exceptions' package.
> 
> Sample code:
> 
> ```
> Amplituda amplituda = new Amplituda();
> amplituda.setErrorListener(error -> {
>     error.printStackTrace() // Print error message
>     if(error instanceof AmplitudaIOException) { // Handle only io exceptions
>         System.out.println("IO exception");
>     }
>     // etc
> });
> ```
> 
> Have a nice day :)

Awesome! Thank you)
