### ISSUE TITLE
Error - FORTIFY: fprintf: null FILE*

### ISSUE THREAD

**Issue by harshitjain0803** [lincollincol/Amplituda#13]
Hi,

I am using this library to display waveform from an mp3 file.

`Amplituda amplituda = new Amplituda(getContext());
        amplituda.fromPath(audioFile.getPath())
                .amplitudesAsList(list -> {
                    waveFormSeekbar.setSample(ArrayUtils.toPrimitiveArray(list));
});`

But its crashing. And in logs only this line is getting printed.
A/libc: FORTIFY: fprintf: null FILE*
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 3330

**Comment by lincollincol** [comment]
@harshitjain0803 Hi! What about read and write permissions?

**Comment by harshitjain0803** [comment]
@lincollincol - Yes, read and write permissions have been provided.

**Comment by lincollincol** [comment]
@harshitjain0803 Fine, send me your audio file to xlincollincolx@gmail.com (or you can attach it here) and I'll try to reproduce this bug

**Comment by harshitjain0803** [comment]
Hi @lincollincol, I have mailed you the file.

**Comment by lincollincol** [comment]
Hi @harshitjain0803, try this build: `implementation 'com.github.lincollincol:amplituda:db1d47aa3b'`

Use this build only for testing. Let me know if it works, I will release a new version of Amplituda library

**Comment by harshitjain0803** [comment]
Hi @lincollincol,

It is still crashing.

**Comment by lincollincol** [comment]
@harshitjain0803 
- What is your android version? 
- Do you use multithreading in your code (if yes - which tool do you use)?
- How many times do you call `amplituda.fromPath(path)` before the crash?
- Which "WaveformSeekBar" library version do you use in your project?

**Comment by harshitjain0803** [comment]
Hi @lincollincol,

- What is your android version? - Android version 9+.
- Do you use multithreading in your code (if yes - which tool do you use)? - No
- How many times do you call amplituda.fromPath(path) before the crash? - I have multiple audio files, so this code is called multiple times. But crash happens when the I call this code on same file second time, after restarting the app. (There is a scenario where the user is logged out of the app and has to relogin into the app. After relogin when this amplituda.fromPath(path) is called the app crashes).
- Which "WaveformSeekBar" library version do you use in your project? - com.github.massoudss:waveformSeekBar:3.0.0

**Comment by lincollincol** [comment]
@harshitjain0803 try this build only for testing
`implementation 'com.github.lincollincol:amplituda:e6ff2695d9'`

**Comment by harshitjain0803** [comment]
Hi @lincollincol,

Its working fine on the above build.

**Comment by lincollincol** [comment]
Hi @harshitjain0803, I'll release new stable Amplituda version this week.

**Comment by harshitjain0803** [comment]
Hi @lincollincol,

Can I use this till then? 'implementation 'com.github.lincollincol:amplituda:e6ff2695d9'

**Comment by lincollincol** [comment]
@harshitjain0803 I haven't tested this version very well, but yes, you can use it until a new stable version is out.

**Comment by lincollincol** [comment]
Hi @harshitjain0803, now you can use `implementation 'com.github.lincollincol:Amplituda:2.0.1'`. Thank you for this bug report, good luck!

**Comment by harshitjain0803** [comment]
Thank you @lincollincol for the support. This has helped me a lot.
