### ISSUE TITLE
Taking long time to process with large files, expecting progressive count down to show time to complete process.

### ISSUE THREAD

**Issue by akashmi** [lincollincol/Amplituda#21]
I have used this library in my application. and it's working fine.

But there is no way to get progressive/countdown time to when the process will be completed.
It is taking longer to get amplitudes for the large audio files. and in that case, I want to show the percentage of the completed process for a better user experience.

It will be a rock if you can provide this feature in the same library.

**Comment by UnateD** [comment]
@lincollincol I ran into a similar error. The problem is not with the audio, but with how the processing is done. If Amplitude is accessed in a loop, in several threads, a similar situation arises.

> I tried the above code as you advised, getting below error
> 
> ```
> Failed to convert to modern format file descriptor
>     java.io.IOException: Input file descriptor already original
>         at android.provider.MediaStore.getOriginalMediaFormatFileDescriptor(MediaStore.java:943)
>         at android.os.FileUtils.convertToModernFd(FileUtils.java:1470)
>         at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:304)
>         at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:250)
>         at linc.com.amplituda.FileManager.getAudioDuration(FileManager.java:58)
>         at linc.com.amplituda.Amplituda.processFileJNI(Amplituda.java:54)
>         at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:83)
> ```

**Comment by lincollincol** [comment]
@akashmi Hi, now you can use progress listener:
* Update Amplituda version to 2.1.1
`implementation 'com.github.lincollincol:amplituda:v2.1.1'`

* Pass `AmplitudaProgressListener` 

```
Amplituda amplituda = new Amplituda(this);

amplituda.processAudio(
"/storage/emulated/0/Music/Linc - Amplituda.mp3",
Compress.withParams(Compress.AVERAGE, 1),
new AmplitudaProgressListener() {
@Override
public void onStartProgress() {
super.onStartProgress();
System.out.println("Start Progress");
}

@Override
public void onStopProgress() {
super.onStopProgress();
System.out.println("Stop Progress");
}

@Override
public void onProgress(ProgressOperation operation, int progress) {
String currentOperation = "";
switch (operation) {
case PROCESSING: currentOperation = "Process audio"; break;
case DECODING: currentOperation = "Decode resource"; break;
case DOWNLOADING: currentOperation = "Download audio from url"; break;
}
System.out.printf("%s: %d%% %n", currentOperation, progress);
}
}
).get(result -> { 
// handle result
}, exception -> { 
exception.printStackTrace(); });
```
