### ISSUE TITLE
Does Amplituda project's ffmpeg can compile for ios?

### ISSUE THREAD

**Issue by g707175425** [lincollincol/Amplituda#28]
Hi, excuse me, does Amplituda project's ffmpeg can compile for ios? Thank you so much for your help.🤝

**Comment by lincollincol** [comment]
@g707175425 Hello. I haven't worked with IOS, but I think it's possible.
Here is a project on <a href="https://github.com/kewlbear/FFmpeg-iOS-build-script">github</a> with a script to compile FFMPEG for IOS. After you compile the .so libraries, you can try the Amplituda C code from this project.

If you want to extend Amplituda for IOS platform - let me know if I can help in something else.

**Comment by g707175425** [comment]
Ok,i'm very appreciate it for your help.

**Comment by g707175425** [comment]
> @g707175425 Hello. I haven't worked with IOS, but I think it's possible.
> Here is a project on <a href="https://github.com/kewlbear/FFmpeg-iOS-build-script">github</a> with a script to compile FFMPEG for IOS. After you compile the .so libraries, you can try the Amplituda C code from this project.
> 
> If you want to extend Amplituda for IOS platform - let me know if I can help in something else.

Ok,i'm very appreciate it for your help.
