### ISSUE TITLE
Codec not found error

### ISSUE THREAD

**Issue by gaynor** [lincollincol/Amplituda#29]
I am recording audio files through android using the MediaRecorder. When I try to process the audio file i get the following error:

"linc.com.amplituda.exceptions.processing.CodecNotFoundException: Failed to find codec!"

**Comment by lincollincol** [comment]
@gaynor Hi! This is cause Amplituda doesn't support `AMR_NB` codec. 
Try to replace it on `AAC`, `OPUS`, `VORBIS` [. . .] and record the audio file with format according to one of the codecs.

I tested it with this <a href="https://developer.android.com/guide/topics/media/mediarecorder">code</a> by replacing 
`setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB)` to `setAudioEncoder(MediaRecorder.AudioEncoder.AAC)` and output audio file format to `.aac`

**Comment by gaynor** [comment]
Awesome. That solved it. This library is a life saver :)

**Comment by FarhanAhmad** [comment]
Do you get proper sample values? I am using the same configuration but I receive sample list not greater then 10. mostly they are 0s.
For example: [0, 0, 0, 0, 0, 2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 6, 3, 2, 0, 1, 1, 3, 3, 1, 0, 0, 0, 3, 2, 1, 1, 1, 4, 0, 0, 1, 2, 2, 2, 3, 2, 1, 1, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 6, 7, 1, 6, 5, 4, 2, 2, 1, 3, 1, 1, 1, 1, 0, 0]
