### ISSUE TITLE
How can we used with 'ffmpeg-kit'?

### ISSUE THREAD

**Issue by Krunal-K-SimformSolutions** [lincollincol/Amplituda#35]
**Describe the bug**
When we used ffmpeg-kit with 'amplituda' then it give to error for the duplicate file path when merging native libs. Also, i am trying to 'packagingOptions' option but have not succeeded.

**Screenshots**
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libavcodec.so' from inputs:
      - /Users/krunal.kevadiya/.gradle/caches/transforms-3/73e9ddb87dcbcf7f33e4d77e2fff8606/transformed/jetified-Amplituda-1.3/jni/arm64-v8a/libavcodec.so
      - /Users/krunal.kevadiya/.gradle/caches/transforms-3/a4e37ee8cddd722ecef5cfd1c70207be/transformed/jetified-ffmpeg-kit-full-4.5/jni/arm64-v8a/libavcodec.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android
 - Version - 2.1.2

```
dependencies {
    implementation 'com.arthenica:ffmpeg-kit-full:4.5'
    implementation  'com.github.massoudss:waveformSeekBar:4.1.0'
    implementation 'com.github.lincollincol:Amplituda:2.1.2'
}
```

**Comment by lincollincol** [comment]
Hi! Please add this code to your `build.gradle(:app)` and try again

```
packagingOptions {
    pickFirst 'lib/*/libavcodec.so'
    pickFirst 'lib/*/libavformat.so'
    pickFirst 'lib/*/libavutil.so'
    pickFirst 'lib/*/libswresample.so'
}
```

**Comment by Krunal-K-SimformSolutions** [comment]
@lincollincol: I am already trying it and it's successfully run but when I have used the feature then the app crash.

**Comment by kid9591** [comment]
I also got crash when using with ffmpeg-kit. Please help.

**Comment by jasperWang** [comment]
> @lincollincol: I am already trying it and it's successfully run but when I have used the feature then the app crash.
> 
> Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-lib.so" not found


Have you solved this problem? I have the same problem

**Comment by Krunal-K-SimformSolutions** [comment]
hi @jasperWang, can you please try the below solution if works for your case in my case I am resolved using the below code. 

dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS'
    implementation  'com.github.massoudss:waveformSeekBar:4.1.0'
    implementation 'com.github.lincollincol:Amplituda:2.1.2'
}

packagingOptions {
       pickFirst "lib/x86/libc++_shared.so"
       pickFirst "lib/arm64-v8a/libc++_shared.so"
       pickFirst "lib/x86_64/libc++_shared.so"
       pickFirst "lib/armeabi-v7a/libc++_shared.so"

       pickFirst 'lib/*/libavcodec.so'
       pickFirst 'lib/*/libavformat.so'
       pickFirst 'lib/*/libavutil.so'
       pickFirst 'lib/*/libswresample.so'
   }

**Comment by jasperWang** [comment]
> com.arthenica:
@Krunal-K-SimformSolutions Thank you ，very good advice

**Comment by szkodnik25** [comment]
@lincollincol 
Bumping this up - even though it compiles after adding

```
packagingOptions {
    pickFirst 'lib/*/libavcodec.so'
    pickFirst 'lib/*/libavformat.so'
    pickFirst 'lib/*/libavutil.so'
    pickFirst 'lib/*/libswresample.so'
}
```

It crashes when I attempt to execute a command with `FFMpegKit`:

```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_log_default_callback" referenced by "/data/app/~~vcC-Dd3wGUD7H5g08uGwYw==/<package-name>-2ifFi07zE-pLXwBgN_WCCw==/base.apk!/lib/arm64-v8a/libffmpegkit.so"
```

I assume it happens because you have all FFmpeg `.so` files embedded into the project, and when somebody wants to use your library with `FFmpegKit` (which also contains the same `.so` files) it fails with files collision.
Probably `pickFirst` picks the "wrong" file for the `FFmpegKit` and that's why it fails.

**Comment by BayuWijayaPermanaPutra** [comment]
I'm used last version of ffmpeg-kit (4.5) and amplituda 2.1.4

Already packagingOptions to pickFirst lib.

packagingOptions {
    pickFirst 'lib/*/libavcodec.so'
    pickFirst 'lib/*/libavformat.so'
    pickFirst 'lib/*/libavutil.so'
    pickFirst 'lib/*/libswresample.so'
}

but I have another UnsatisfiedLinkError crash at runtime too.

> E/AndroidRuntime: FATAL EXCEPTION: main
>     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "avcodec_free_context" referenced by "/[data/app/~~_1u8UG-B6pk6UuupIQUWKw==/<package-name>-eHFK4PC6dyMU0GRNI0c7ig==/base.apk!/lib/arm64-v8a/libnative-lib.so](http://data/app/~~_1u8UG-B6pk6UuupIQUWKw==/<package-name>-eHFK4PC6dyMU0GRNI0c7ig==/base.apk!/lib/arm64-v8a/libnative-lib.so)"...

**Comment by xiaoyvyv** [comment]
> 我使用的是最新版本的 ffmpeg-kit (4.5) 和 amplituda 2.1.4
> 
> 已经为pickFirst lib提供了packagingOptions。
> 
> ```
> packagingOptions {
>     pickFirst 'lib/*/libavcodec.so'
>     pickFirst 'lib/*/libavformat.so'
>     pickFirst 'lib/*/libavutil.so'
>     pickFirst 'lib/*/libswresample.so'
> }
> ```
> 
> 但我在运行时也有另一个 UnsatisfiedLinkError 崩溃。
> 
> ```
> E/AndroidRuntime: FATAL EXCEPTION: main
>     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "avcodec_free_context" referenced by "/[data/app/~~_1u8UG-B6pk6UuupIQUWKw==/<package-name>-eHFK4PC6dyMU0GRNI0c7ig==/base.apk!/lib/arm64-v8a/libnative-lib.so](http://data/app/~~_1u8UG-B6pk6UuupIQUWKw==/<package-name>-eHFK4PC6dyMU0GRNI0c7ig==/base.apk!/lib/arm64-v8a/libnative-lib.so)"...
> ```

the same as

**Comment by lincollincol** [comment]
@jasperWang @kid9591 @BayuWijayaPermanaPutra @xiaoyvyv 

`implementation 'com.github.lincollincol:Amplituda:v2.1.5'`
