### ISSUE TITLE
The result of the process is empty on Android 10

### ISSUE THREAD

**Issue by MahdiDavoodi** [lincollincol/Amplituda#38]
Hey there. I have a problem and I think it's related to my code. But I'm not sure and I need to ask:

## Description

The following code is setting an on long click listener for an `ImageButton`. The `newWaveForm` is the result of the processed array from amplituda.

```kotlin
npa_pause_ib.setOnLongClickListener {
    val newWaveForm =
        Amplituda(this).processAudio(SiQueue.getTrackToPlay().path).get().amplitudesAsList()
            .toIntArray()
    if (newWaveForm.isNotEmpty()) {
        SiQueue.defaultSamples = newWaveForm
        npa_sb.setSampleFrom(SiQueue.defaultSamples)
    } else {
        Toast.makeText(this, "Something went wrong!", Toast.LENGTH_SHORT).show()
        Log.e(TAG, "The result of Amplituda is empty.")
        Log.d(TAG, SiQueue.getTrackToPlay().toString())
    }
    true
}

```

### Logs
```java
2022-02-18 15:07:16.608 23906-23906/davoodi.mahdi.sievere E/NowPlayingActivity: The result of Amplituda is empty.
2022-02-18 15:07:16.608 23906-23906/davoodi.mahdi.sievere D/NowPlayingActivity: Track(context=davoodi.mahdi.sievere.activities.IntroActivity@a064f9d, id=27, uri=content://media/external/audio/media/27, path=/storage/18FF-1F12/Music/02 Mansionair - Alibi.mp3, fileName=02 Mansionair - Alibi.mp3, setTitle=Alibi, setArtist=Mansionair, setAlbum=Shadowboxer)
```
**The problem is**: in devices that are running Android 10, the result is always empty.

I've tested this with the exact same file on 8 devices. I only have this problem with Android 10.

How can I solve this?

Thank you.

**Comment by MahdiDavoodi** [comment]
Hello @lincollincol. Thank you for your time.

As I said before, I think there is a problem with how I use Amplituda, not with Amplituda itself. (So consider this as a question rather than a real issue)

The problem I mentioned, is not about a single file. Every mp3 file that I tested, had the same issue on Android 10.

- Expected behavior on [Android 9](https://github.com/MahdiDavoodi/MahdiDavoodi/blob/main/temp/android9.gif).
- The empty result on [Android 10](https://github.com/MahdiDavoodi/MahdiDavoodi/blob/main/temp/android10.gif).

Since you asked, here is the exact [file](https://github.com/MahdiDavoodi/MahdiDavoodi/blob/main/temp/02%20Mansionair%20-%20Alibi.mp3) I mentioned in the Logs. You can also check the whole [now playing activity](https://github.com/MahdiDavoodi/Sievere/blob/master/app/src/main/java/davoodi/mahdi/sievere/activities/NowPlayingActivity.kt) if you want.

The app that I'm working on is a mess and currently has so many other issues. I'd be happy to share the debug build with you. But it has some other issues that make the app unusable.

**Comment by lincollincol** [comment]
@MahdiDavoodi Thank you for your feedback and provided resources. So, android 10 has changed the file access permissions

**Case 1:**
If you want to access audio with java File or by it path, you should 
* grant permissions (`READ_EXTERNAL_STORAGE`)
* add `android:requestLegacyExternalStorage="true"` to `<application>`

Now, Amplituda will process your file without errors.

**Case 2:**
If you don't want to use `requestLegacyExternalStorage` 
* update Amplituda version to 2.1.4 (`implementation 'com.github.lincollincol:amplituda:2.1.4'`) 
* process audio as `InputStream` or `ByteArray` (example code below)

``` kotlin
val audioStream = contentResolver.openInputStream(SiQueue.getTrackToPlay().uri)
val newWaveForm = amplituda.processAudio(audioStream)
    .get()
    .amplitudesAsList()
    .toIntArray()
```

**Comment by MahdiDavoodi** [comment]
@lincollincol 

_Thank you_. _**Thank you**_. _**THANK YOU**_. 💫 

Both cases worked just fine. I went with the second case.
