### ISSUE TITLE
You should rename native-lib to some meaningfull name as other proejcts somehow like to use this too what makes build issues...

### ISSUE THREAD

**Issue by renetik** [lincollincol/Amplituda#41]
I believe this is bug to use common name like this as if other library use it as well you have to fork one and edti manualy to be able to use both in same project. It happened to me so just a suggestion/bug to improve project ;)

**Comment by szkodnik25** [comment]
@renetik 
Hello! Could you elaborate more on how you've managed to do that? Did you just rename conflicting `.so` files?

**Comment by renetik** [comment]
So the poroblem is in CMakeLists.txt 
`add_library(native-lib .... 

They basically defined name `native-lib` and looks like this can cause problem s when mixing multiple native libraries in android.
What I did was that I renamed my own native code to more meaningful name so it don colide with this...

So now I have `add_library(renetik-instruments-library-audio SHARED ${native_lib_sources} ${cpp_src})` before I ha there add_library(native-lib SHARED ${native_lib_sources} ${cpp_src}) and it did some kind of conflict..

**Comment by lincollincol** [comment]
@renetik `implementation 'com.github.lincollincol:Amplituda:v2.1.5'`
