### ISSUE TITLE
Multithread decoding

### ISSUE THREAD

**Issue by voliothonh** [lincollincol/Amplituda#44]
**Describe the bug**
- Use multithread to decode multiple file will get Exception

**Smartphone (please complete the following information):**
- All devices

W/System.err: Read Amplituda doc here: https://github.com/lincollincol/Amplituda
W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getExceptionFromCode(AmplitudaResultJNI.java:94)
W/System.err:     at linc.com.amplituda.AmplitudaResultJNI.getErrors(AmplitudaResultJNI.java:74)
W/System.err:     at linc.com.amplituda.AmplitudaProcessingOutput.<init>(AmplitudaProcessingOutput.java:32)
W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:80)
W/System.err:     at linc.com.amplituda.Amplituda.processAudio(Amplituda.java:33)
W/System.err:     at com.volio.vn.ui.audio.local.yourPhone.MusicOnPhoneEvent$buildModels$1$1$1.invoke(MusicOnPhoneEvent.kt:48)
W/System.err:     at com.volio.vn.ui.audio.local.yourPhone.MusicOnPhoneEvent$buildModels$1$1$1.invoke(MusicOnPhoneEvent.kt:47)
W/System.err:     at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by lincollincol** [comment]
Hello @nmduong99, could you also provide a code sample with Amplituda calls from your project?

**Comment by voliothonh** [comment]
@lincollincol 
![image](https://user-images.githubusercontent.com/102571727/182507217-938f436b-235f-4e21-8fad-87d9e0d101c8.png)
This code I am using in the actual prj


```kotlin
paths.forEach {  path ->
            CoroutineScope(Dispatchers.IO).launch {
                Amplituda(context)
                    .setLogConfig(5, true)
                    .processAudio(path)
                    .get(
                        { result -> },
                        { exception -> exception.printStackTrace() }
                    )
            }
        }
```

**Comment by lincollincol** [comment]
@voliothonh `implementation 'com.github.lincollincol:Amplituda:v2.1.6'`

**Comment by voliothonh** [comment]
@lincollincol It doesn't work :( Pls check again

**Comment by lincollincol** [comment]
@voliothonh Hi! I can't reproduce the application crash. Amplituda also processes audio files sequentially. Parallel processing is not available at the moment

Tested with this code:

``` kotlin
val amplituda = Amplituda(this)
amplituda.setLogConfig(Log.ERROR, true)

CoroutineScope(Dispatchers.IO).launch {
    paths.forEach {
        launch {
            val result = amplituda.processAudio(it).get()
            println(result.amplitudesAsList())
        }
    }
}
```
