### ISSUE TITLE
Support for other formats as well like 3gp,mp4 etc

### ISSUE THREAD

**Issue by mohsin-ali-brainx** [lincollincol/Amplituda#47]
I have a feature where I have to record an audio using Mic which is implemented by using MediaRecorder and it only output file format for .3gp as there is no encoder for .mp3 file to we have to specify the output format in .3gp. 
so when passed this file path it does not create the amplitude for it. I'm using this library with waveformseekbar library in Android.

**Comment by lincollincol** [comment]
Hello @mohsin-ali-brainx. Amplituda supports these audio formats. So, maybe something with a recorded audio file? Could you please provide one of these files?

**Comment by lincollincol** [comment]
@mohsin-ali-brainx Hello. Please, update lib version to 2.2.2 
`implementation 'com.github.lincollincol:amplituda:2.2.2'`

**Comment by lincollincol** [comment]
@raph9091 Hello! Amplituda doesn't support these formats. 
As far as I understand, M3U8 format represents a [playlist (plain text with audio files paths)](https://www.lifewire.com/m3u8-file-2621956). So, maybe you can try to read this file, extract all files and process with Amplituda.
