### ISSUE TITLE
WAV format not working propperly

### ISSUE THREAD

**Issue by qsdigor** [lincollincol/Amplituda#5]
It looks like wav format always returns list of integers with all values 127.

1. Init Amplituda
2. start fromFile() with audio file with wav extension.
3. receive amplitudesAsList callback. 
4. print or debug the received list.

**Expected behavior**
It should work as same as mp3 does with propper waveform

**Comment by lincollincol** [comment]
Hello @qsdigor , I'd like to process your audio file on my machine. Can you attach the file to your new reply?

**Comment by qsdigor** [comment]
Hello @lincollincol , here are my files. On my device all wav files do not work. 
[MP3 working file](https://drive.google.com/file/d/13ZqDAjipqLR5Gfci0pYSBL8i5NRg3g0A/view?usp=sharing)
[WAV issued file](https://drive.google.com/file/d/1uOqRDwuhFZ5A8ifZmzebBRaE6ToGBGsW/view?usp=sharing)

**Comment by qsdigor** [comment]
@lincollincol Hi, any progress on this issue? Thanks

**Comment by lincollincol** [comment]
@qsdigor Hello, yes. We receive unexpected data because of the audio file codec. When I was testing audio processing (during the development), I use wav file with codec pcm_u8. If you try to get more details from the attached file, you'll see that file encoded with pcm_s16le codec. When you change codec to pcm_u8 with ffmpeg and try to process it with Amplituda again, the result will be correct. I'm looking for solutions to fix this bug.

**Comment by qsdigor** [comment]
@lincollincol Good job! Is it something you can fix or will it need new codec support?

**Comment by mdivkovic-speech** [comment]
@lincollincol, I'm working with @qsdigor on this, and if you don't have time but have some idea how it could be fixed, we'll be more than happy to try and make a pull request to fix it - with your suggestions of course.

**Comment by lincollincol** [comment]
@mdivkovic-speech and @qsdigor, good news, guys! I spent a lot of time solving this problem today and now this issue is partially resolved. I need a few days to finish it.

**Comment by mdivkovic-speech** [comment]
@lincollincol Wow, that sounds amazing! Thank you very much, really! It will help us a lot.

**Comment by qsdigor** [comment]
Great job! Thank you.

**Comment by lincollincol** [comment]
@qsdigor, @mdivkovic-speech Update Amplituda to version 1.6

**Comment by mdivkovic-speech** [comment]
Thank you very much! We will try it out first thing on Monday :) Have a great rest of the weekend

**Comment by mdivkovic-speech** [comment]
@lincollincol we tried it out and the waveform looks perfect now, thank you! Do you have a tip jar or something where I could buy you a cup of coffee? After all, you do this for free and you've been very responsive and helpful during this process.

**Comment by lincollincol** [comment]
@mdivkovic-speech Great! Thank you for your response! I hope we will stay in touch.
