### ISSUE TITLE
linc.com.amplituda.exceptions.processing.CodecNotFoundException: Failed to find codec!

### ISSUE THREAD

**Issue by gaynor** [lincollincol/Amplituda#52]
I am now getting the following error in the latest 2.2.1. I have FFMPEGKit in the project as well that I was using to stitch audio files together as 3gp. The last version before the fix to prevent the library conflicts (2.1.4) can read the created audio files fine, but the latest version can't, as I am getting the error in the title. I was wondering if it is because there is a different version of ffmpeg used?Is there a way to use the older ffmpeg files from 2.1.4 and rename them? Or should I be looking at something else? I would stay with using amplituda 2.1.4, but it cannot run alongside ffmpegkit. I have to disable one to test the other.

**Comment by lincollincol** [comment]
@gaynor Hello. Please, update lib version to 2.2.2 
`implementation 'com.github.lincollincol:amplituda:2.2.2'`
