### ISSUE TITLE
Get custom sample count

### ISSUE THREAD

**Issue by SudoDios** [lincollincol/Amplituda#57]
Hi.
Can't get a specific number of amplitudes ?
For example, whether the audio file is 1 minute or 10 minutes, let's get 60 .

**Comment by SudoDios** [comment]
What is the maximum number that this library gives for amplitude ?

**Comment by lincollincol** [comment]
Hello @SudoDios 
Please, check "[Set sampling rate issue](https://github.com/lincollincol/Amplituda/issues/15#issuecomment-877657630)" or you can also check [readme example](https://github.com/lincollincol/Amplituda/issues/15#issuecomment-877657630)

**Comment by SudoDios** [comment]
Here compress is executed for every second. But I want to compress the sound all the time.
for example :
10s -> 60 [samples]
30s -> 60 [samples]
100s -> 60 [samples]
300s -> 60 [samples]
The number of amplitudes should be constant for any time.

**Comment by lincollincol** [comment]
I think it's already described in "[Set sampling rate issue](https://github.com/lincollincol/Amplituda/issues/15)". So, you can take a look at the discussion :)

Not sure we can get exactly 60 samples (or more) for short audio files, but you can add your custom logic for this case (populate 0 or something like that).

Here is an [example](https://github.com/lincollincol/Amplituda/issues/15#issuecomment-1271393660) of `chunkedToSize()` function from issue or you can also use @ThomasArtProcessors `normaliseAmplitudes()` implementation

**Comment by lincollincol** [comment]
By the way, you can also take a look at the [compose-audiowaveform](https://github.com/lincollincol/compose-audiowaveform) library. I used `chunkedToSize()` function from the example above in this library

**Comment by SudoDios** [comment]
Nice.
Thank you.
