### ISSUE TITLE
This release is not compliant with the Google Play 64-bit requirement. The following APKs or app bundles are available to 64-bit devices, but they only have 32-bit native code: [19] Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code that it needs. This avoids increasing the overall size of your app

### ISSUE THREAD

**Issue by shivangbtech** [lincollincol/Amplituda#6]
Issue: This release is not compliant with the Google Play 64-bit requirement.
The following APKs or app bundles are available to 64-bit devices, but they only have 32-bit native code: [19]
Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code that it needs. This avoids increasing the overall size of your app.

The issue is coming because the native library does not support 64-bit.

**Comment by alkurop** [comment]
Only because library does not support x86_64, but there aren't many devices with the architecture, so it should be fine

**Comment by sky003** [comment]
Still kind of a problem because this is the Google Play requirement. I'm going to try to build a 64-bit version, hope that won't be a problem. 

@lincollincol not sure if you have time for this, but are there any possible issues? And thank you for the great library!

**Comment by lincollincol** [comment]
@sky003 today I'm going to push fix for that issue. If you test it, I'll be very grateful!

**Comment by sky003** [comment]
@lincollincol that's would be great! I can help with the testing

**Comment by lincollincol** [comment]
@sky003 Try this one `implementation 'com.github.lincollincol:Amplituda:c62edccfa8'`. Please let me know if this version fixes your problem.

**Comment by sky003** [comment]
> @sky003 Try this one `implementation 'com.github.lincollincol:Amplituda:c62edccfa8'`. Please let me know if this version fixes your problem.

Tested it on x86 and x64 emulators. It works as expected, loads the correct libraries for each architecture. So it should work, thanks! 
Though to be hundred percent sure, it also should be checked in the google play console, but I didn't have a chance to do this
