### ISSUE TITLE
The app crashes when multiple audio are processed

### ISSUE THREAD

**Issue by Miara** [lincollincol/Amplituda#61]
**Describe the bug**
I am developer of Android chat application, and I tried to use [WaveformSeekBar library]( https://github.com/massoudss/waveformSeekBar) to process audio files. This library uses this library. When I was processing multiple audio files in the same time, the app crashed. Stacktrace is here:

![image](https://github.com/lincollincol/Amplituda/assets/7967321/bb96847c-be23-4ca6-b744-ab37b5e641e3)

so it looks like there is some issue in native code `libavcodec-amplituda.so`. Can you please help with this? 

**Other useful information:**
- Tested device: Samsung Galaxy Note 10+ (with Android 12)
- Although the app crashed, stacktrace wasn't visible in the app's logs, but after removing all filter it was visible in whole system's logs
- I wasn't able to reproduce this crash when I loaded single audio, but it doesn't mean that bug wouldn't occur as well in such scenario

**Comment by akteruzzaman816** [comment]
@lincollincol any update on this ?

**Comment by lincollincol** [comment]
https://github.com/lincollincol/Amplituda/issues/44#issuecomment-1212956771

#44
